### Solving Equations
Guass's Method

In [6]:
import numpy as np

### 2 equations we are solving 2x + y = 5, 3x + 2y = 40
matrix = np.asarray([
    [2,1,5],
    [3,2,40]
], dtype=np.float32)
print(matrix)

matrix[0] = matrix[0]*2
print(matrix)

matrix[0] = matrix[0] - matrix[1]
print(matrix)

matrix[1] = matrix[1] - (3*matrix[0])
print(matrix)

matrix[1] = matrix[1] / 2
print(matrix)
## hence the value for x and y are -30 and 65 respectively.

[[ 2.  1.  5.]
 [ 3.  2. 40.]]
[[ 4.  2. 10.]
 [ 3.  2. 40.]]
[[  1.   0. -30.]
 [  3.   2.  40.]]
[[  1.   0. -30.]
 [  0.   2. 130.]]
[[  1.   0. -30.]
 [  0.   1.  65.]]


In [11]:
matrix = np.asarray([
    [1,2,0,7],
    [0,3,3,11],
    [1,2,2,11]
], dtype=np.float32)
print(matrix)

matrix[2] = matrix[2] - matrix[0]
print(matrix)

matrix[2] = matrix[2]/2
print(matrix)

matrix[1] = matrix[1] - (3*matrix[2])

matrix[1] = matrix[1]/3
print(matrix,"\n")

matrix[0] = matrix[0] - (2*matrix[1])
print(matrix)


[[ 1.  2.  0.  7.]
 [ 0.  3.  3. 11.]
 [ 1.  2.  2. 11.]]
[[ 1.  2.  0.  7.]
 [ 0.  3.  3. 11.]
 [ 0.  0.  2.  4.]]
[[ 1.  2.  0.  7.]
 [ 0.  3.  3. 11.]
 [ 0.  0.  1.  2.]]
[[1.        2.        0.        7.       ]
 [0.        1.        0.        1.6666666]
 [0.        0.        1.        2.       ]] 

[[1.        0.        0.        3.6666667]
 [0.        1.        0.        1.6666666]
 [0.        0.        1.        2.       ]]


### Echelon Form

In [12]:
matrix = np.asarray([
    [0,0,0,7],
    [0,0,1,11],
    [1,2,2,11],
    [0,5,5,1]
], dtype=np.float32)
print(matrix)

matrix[[0,2]] = matrix[[2,0]]
print(matrix)

matrix[[1,3]] = matrix[[3,1]]
print(matrix)

matrix[[2,3]] = matrix[[3,2]]
print(matrix)

[[ 0.  0.  0.  7.]
 [ 0.  0.  1. 11.]
 [ 1.  2.  2. 11.]
 [ 0.  5.  5.  1.]]
[[ 1.  2.  2. 11.]
 [ 0.  0.  1. 11.]
 [ 0.  0.  0.  7.]
 [ 0.  5.  5.  1.]]
[[ 1.  2.  2. 11.]
 [ 0.  5.  5.  1.]
 [ 0.  0.  0.  7.]
 [ 0.  0.  1. 11.]]
[[ 1.  2.  2. 11.]
 [ 0.  5.  5.  1.]
 [ 0.  0.  1. 11.]
 [ 0.  0.  0.  7.]]


In [13]:
### Reduced Row Echolean Form

### Inconsistency

In [14]:
### where we cannot find any solutions

### Infinite Solutions

In [15]:
### Having Infinite Solutions

### Homogeneity

In [16]:
### If the linear equaltions have a contant of zero
### Ex -  3x + 4y = 0

### Singularity

In [17]:
### when we can simplify the equations 